# Generated by Django 4.2.23 on 2025-06-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranking',
            name='group',
        ),
        migrations.RemoveField(
            model_name='ranking',
            name='user',
        ),
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
        migrations.RemoveField(
            model_name='taskprogresslog',
            name='task_id',
        ),
        migrations.RemoveField(
            model_name='taskprogresslog',
            name='user',
        ),
        migrations.RemoveField(
            model_name='video_session',
            name='host',
        ),
        migrations.DeleteModel(
            name='note',
        ),
        migrations.DeleteModel(
            name='ranking',
        ),
        migrations.DeleteModel(
            name='task',
        ),
        migrations.DeleteModel(
            name='TaskProgressLog',
        ),
        migrations.DeleteModel(
            name='video_session',
        ),
    ]
