# Generated by Django 4.2.21 on 2025-05-14 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouping', '0002_rename_rooms_room_rename_desciption_room_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='join_code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
