# Generated by Django 4.2.21 on 2025-05-22 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersession',
            name='login_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
