# Generated by Django 4.2.21 on 2025-06-10 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_usersession_login_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSession',
        ),
    ]
