# Generated by Django 4.2.21 on 2025-06-11 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_usersession_session_key_alter_usersession_login_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersession',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
