# Generated by Django 4.2.21 on 2025-05-18 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grouping', '0003_room_join_code'),
        ('zfeng', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workspace', to='grouping.room'),
        ),
    ]
