# Generated by Django 4.2.21 on 2025-05-26 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grouping', '0004_document'),
        ('zfeng', '0003_alter_todo_assigned_to_alter_todo_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='document',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='grouping.document'),
        ),
    ]
